/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cstr_ode_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* cstr_ode_expl_vde_forw:(i0[3],i1[3x3],i2[3x2],i3[2],i4)->(o0[3],o1[3x3],o2[3x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[4]? arg[4][0] : 0;
  a1=1.;
  a2=arg[0]? arg[0][0] : 0;
  a1=(a1-a2);
  a1=(a0*a1);
  a3=1.5067392525882006e-01;
  a4=arg[0]? arg[0][2] : 0;
  a5=1.0000000000000001e-05;
  a4=(a4+a5);
  a4=(a3*a4);
  a1=(a1/a4);
  a5=72000000000.;
  a6=-8750.;
  a7=arg[0]? arg[0][1] : 0;
  a6=(a6/a7);
  a8=exp(a6);
  a9=(a5*a8);
  a10=(a9*a2);
  a11=(a1-a10);
  if (res[0]!=0) res[0][0]=a11;
  a11=350.;
  a11=(a11-a7);
  a11=(a0*a11);
  a11=(a11/a4);
  a12=-2.0920502092050208e+02;
  a10=(a12*a10);
  a10=(a11-a10);
  a13=2.0993102921228100e+00;
  a14=arg[3]? arg[3][0] : 0;
  a14=(a14-a7);
  a14=(a13*a14);
  a10=(a10+a14);
  if (res[0]!=0) res[0][1]=a10;
  a10=arg[3]? arg[3][1] : 0;
  a10=(a0-a10);
  a10=(a10/a3);
  if (res[0]!=0) res[0][2]=a10;
  a10=arg[1]? arg[1][0] : 0;
  a14=(a0*a10);
  a14=(a14/a4);
  a15=(a1/a4);
  a16=arg[1]? arg[1][2] : 0;
  a16=(a3*a16);
  a17=(a15*a16);
  a14=(a14+a17);
  a10=(a9*a10);
  a17=(a6/a7);
  a18=arg[1]? arg[1][1] : 0;
  a19=(a17*a18);
  a19=(a8*a19);
  a19=(a5*a19);
  a19=(a2*a19);
  a10=(a10-a19);
  a14=(a14+a10);
  a14=(-a14);
  if (res[1]!=0) res[1][0]=a14;
  a14=(a0*a18);
  a14=(a14/a4);
  a19=(a11/a4);
  a16=(a19*a16);
  a14=(a14+a16);
  a10=(a12*a10);
  a14=(a14+a10);
  a18=(a13*a18);
  a14=(a14+a18);
  a14=(-a14);
  if (res[1]!=0) res[1][1]=a14;
  a14=0.;
  if (res[1]!=0) res[1][2]=a14;
  a18=arg[1]? arg[1][3] : 0;
  a10=(a0*a18);
  a10=(a10/a4);
  a16=arg[1]? arg[1][5] : 0;
  a16=(a3*a16);
  a20=(a15*a16);
  a10=(a10+a20);
  a18=(a9*a18);
  a20=arg[1]? arg[1][4] : 0;
  a21=(a17*a20);
  a21=(a8*a21);
  a21=(a5*a21);
  a21=(a2*a21);
  a18=(a18-a21);
  a10=(a10+a18);
  a10=(-a10);
  if (res[1]!=0) res[1][3]=a10;
  a10=(a0*a20);
  a10=(a10/a4);
  a16=(a19*a16);
  a10=(a10+a16);
  a18=(a12*a18);
  a10=(a10+a18);
  a20=(a13*a20);
  a10=(a10+a20);
  a10=(-a10);
  if (res[1]!=0) res[1][4]=a10;
  if (res[1]!=0) res[1][5]=a14;
  a10=arg[1]? arg[1][6] : 0;
  a20=(a0*a10);
  a20=(a20/a4);
  a18=arg[1]? arg[1][8] : 0;
  a18=(a3*a18);
  a15=(a15*a18);
  a20=(a20+a15);
  a10=(a9*a10);
  a15=arg[1]? arg[1][7] : 0;
  a17=(a17*a15);
  a17=(a8*a17);
  a17=(a5*a17);
  a17=(a2*a17);
  a10=(a10-a17);
  a20=(a20+a10);
  a20=(-a20);
  if (res[1]!=0) res[1][6]=a20;
  a20=(a0*a15);
  a20=(a20/a4);
  a19=(a19*a18);
  a20=(a20+a19);
  a10=(a12*a10);
  a20=(a20+a10);
  a15=(a13*a15);
  a20=(a20+a15);
  a20=(-a20);
  if (res[1]!=0) res[1][7]=a20;
  if (res[1]!=0) res[1][8]=a14;
  a20=arg[2]? arg[2][0] : 0;
  a15=(a0*a20);
  a15=(a15/a4);
  a1=(a1/a4);
  a10=arg[2]? arg[2][2] : 0;
  a10=(a3*a10);
  a19=(a1*a10);
  a15=(a15+a19);
  a20=(a9*a20);
  a6=(a6/a7);
  a7=arg[2]? arg[2][1] : 0;
  a19=(a6*a7);
  a19=(a8*a19);
  a19=(a5*a19);
  a19=(a2*a19);
  a20=(a20-a19);
  a15=(a15+a20);
  a15=(-a15);
  if (res[2]!=0) res[2][0]=a15;
  a15=(a0*a7);
  a15=(a15/a4);
  a11=(a11/a4);
  a10=(a11*a10);
  a15=(a15+a10);
  a20=(a12*a20);
  a15=(a15+a20);
  a7=(a13*a7);
  a15=(a15+a7);
  a15=(a13-a15);
  if (res[2]!=0) res[2][1]=a15;
  if (res[2]!=0) res[2][2]=a14;
  a14=arg[2]? arg[2][3] : 0;
  a15=(a0*a14);
  a15=(a15/a4);
  a7=arg[2]? arg[2][5] : 0;
  a3=(a3*a7);
  a1=(a1*a3);
  a15=(a15+a1);
  a9=(a9*a14);
  a14=arg[2]? arg[2][4] : 0;
  a6=(a6*a14);
  a8=(a8*a6);
  a5=(a5*a8);
  a2=(a2*a5);
  a9=(a9-a2);
  a15=(a15+a9);
  a15=(-a15);
  if (res[2]!=0) res[2][3]=a15;
  a0=(a0*a14);
  a0=(a0/a4);
  a11=(a11*a3);
  a0=(a0+a11);
  a12=(a12*a9);
  a0=(a0+a12);
  a13=(a13*a14);
  a0=(a0+a13);
  a0=(-a0);
  if (res[2]!=0) res[2][4]=a0;
  a0=-6.6368484014885158e+00;
  if (res[2]!=0) res[2][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cstr_ode_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cstr_ode_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cstr_ode_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cstr_ode_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cstr_ode_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cstr_ode_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cstr_ode_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void cstr_ode_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cstr_ode_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cstr_ode_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real cstr_ode_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cstr_ode_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cstr_ode_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cstr_ode_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cstr_ode_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cstr_ode_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
