/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cstr_ode_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[12] = {3, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s5[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s6[7] = {3, 2, 0, 1, 2, 1, 2};
static const casadi_int casadi_s7[3] = {3, 0, 0};

/* cstr_ode_impl_dae_fun_jac_x_xdot_u_z:(i0[3],i1[3],i2[2],i3[],i4[],i5)->(o0[3],o1[3x3,6nz],o2[3x3,3nz],o3[3x2,2nz],o4[3x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[5]? arg[5][0] : 0;
  a2=1.;
  a3=arg[0]? arg[0][0] : 0;
  a4=(a2-a3);
  a4=(a1*a4);
  a5=1.5067392525882006e-01;
  a6=arg[0]? arg[0][2] : 0;
  a7=1.0000000000000001e-05;
  a6=(a6+a7);
  a6=(a5*a6);
  a4=(a4/a6);
  a7=72000000000.;
  a8=-8750.;
  a9=arg[0]? arg[0][1] : 0;
  a8=(a8/a9);
  a10=exp(a8);
  a11=(a7*a10);
  a12=(a11*a3);
  a13=(a4-a12);
  a0=(a0-a13);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a13=350.;
  a13=(a13-a9);
  a13=(a1*a13);
  a13=(a13/a6);
  a14=-2.0920502092050208e+02;
  a12=(a14*a12);
  a12=(a13-a12);
  a15=2.0993102921228100e+00;
  a16=arg[2]? arg[2][0] : 0;
  a16=(a16-a9);
  a15=(a15*a16);
  a12=(a12+a15);
  a0=(a0-a12);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a12=arg[2]? arg[2][1] : 0;
  a12=(a1-a12);
  a12=(a12/a5);
  a0=(a0-a12);
  if (res[0]!=0) res[0][2]=a0;
  a0=(a1/a6);
  a0=(a0+a11);
  if (res[1]!=0) res[1][0]=a0;
  a11=(a14*a11);
  if (res[1]!=0) res[1][1]=a11;
  a8=(a8/a9);
  a10=(a10*a8);
  a7=(a7*a10);
  a3=(a3*a7);
  a7=(-a3);
  if (res[1]!=0) res[1][2]=a7;
  a14=(a14*a3);
  a1=(a1/a6);
  a14=(a14-a1);
  a1=-2.0993102921228100e+00;
  a14=(a14+a1);
  a14=(-a14);
  if (res[1]!=0) res[1][3]=a14;
  a4=(a4/a6);
  a4=(a5*a4);
  if (res[1]!=0) res[1][4]=a4;
  a13=(a13/a6);
  a5=(a5*a13);
  if (res[1]!=0) res[1][5]=a5;
  if (res[2]!=0) res[2][0]=a2;
  if (res[2]!=0) res[2][1]=a2;
  if (res[2]!=0) res[2][2]=a2;
  if (res[3]!=0) res[3][0]=a1;
  a1=6.6368484014885158e+00;
  if (res[3]!=0) res[3][1]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int cstr_ode_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cstr_ode_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cstr_ode_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cstr_ode_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cstr_ode_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cstr_ode_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cstr_ode_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void cstr_ode_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cstr_ode_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int cstr_ode_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real cstr_ode_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cstr_ode_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cstr_ode_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cstr_ode_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cstr_ode_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cstr_ode_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
